/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Maita
 * Created: 26/02/2018
 */
DROP TABLE USUARIO;
DROP TABLE CLIENTE;
DROP TABLE PRODUCTO;



CREATE TABLE CLIENTE(IDCLIENTE INT AUTO_INCREMENT PRIMARY KEY, IDUSUARIO INT, NOMBRE VARCHAR(30), APELLIDO VARCHAR(30), TELEFONO VARCHAR(30), DIRECCION VARCHAR(100));

CREATE TABLE USUARIO ( IDUSUARIO INT AUTO_INCREMENT PRIMARY KEY, CORREO VARCHAR(30), CLAVE VARCHAR(50));

CREATE TABLE PRODUCTO(IDPRODUCTO INT AUTO_INCREMENT PRIMARY KEY, NOMBRE_P VARCHAR(30),DESCRIPCION VARCHAR(250),COLOR VARCHAR(20), PRECIO FLOAT,  IMAGEN VARCHAR(50));

CREATE TABLE INVENTARIO (IDINVENTARIO INT AUTO_INCREMENT PRIMARY KEY , IDPRODUCTO INT , TALLA VARCHAR(4), CANTIDAD INT);
 

/******sistema de compra y envios Rouxa******/

DROP TABLE PEDIDOS;
DROP TABLE COMPRAS;
DROP TABLE ITEMS;
DROP TABLE ENVIOS;



CREATE TABLE PEDIDOS (IDPEDIDO VARCHAR(32) PRIMARY KEY , CLIENTE VARCHAR(50), TELEFONO VARCHAR(20), EMAIL VARCHAR(50), ESTATUS INT, FECHAPEDIDO DATE);

CREATE TABLE COMPRAS (IDCOMPRA INT AUTO_INCREMENT PRIMARY KEY, IDPEDIDO VARCHAR(32) , MONTO DOUBLE, RAZONSOCIAL VARCHAR(100), RIFCI VARCHAR(40),  DIRFISCAL VARCHAR(200), FECHAPAGO DATE);

CREATE TABLE ITEMS (IDPEDIDO VARCHAR(32),IDINVENTARIO INT , CANTIDAD INT UNSIGNED,  PRECIO DOUBLE);


CREATE TABLE ENVIOS (IDENVIO  INT AUTO_INCREMENT PRIMARY KEY,  IDPEDIDO VARCHAR(32) , PAIS VARCHAR(30), ESTADO VARCHAR(30), CIUDAD VARCHAR(30),MUNICIPIO VARCHAR(30), PARROQUIA VARCHAR(30), DIRECCION VARCHAR(200) , CODIGOPOSTAL VARCHAR(20),RECEPTOR VARCHAR(30), CIRECEPTOR VARCHAR(40),  TELFRECEPTOR VARCHAR(30), OBSERVACIONES VARCHAR(100) , GUIA VARCHAR(50));
/******sistema de compra y envios Rouxa******/



CREATE TABLE VARIABLES( IDVARIABLE INT AUTO_INCREMENT PRIMARY KEY, NOMBRE VARCHAR(10), VALUE INT);

/*
SIMBOLOGIA 

VPP-visitas de pagina principal
CS-compras solicitadas
CF-compras fallidas
CE-compras exitosas
CP-compras pendientes 

*/

/*Creacion de variables iniciales */
INSERT INTO `VARIABLES`(`NOMBRE`, `VALUE`) VALUES ('VPP','0');
INSERT INTO `VARIABLES`(`NOMBRE`, `VALUE`) VALUES ('CS','0');
INSERT INTO `VARIABLES`(`NOMBRE`, `VALUE`) VALUES ('CF','0');
INSERT INTO `VARIABLES`(`NOMBRE`, `VALUE`) VALUES ('CE','0');
INSERT INTO `VARIABLES`(`NOMBRE`, `VALUE`) VALUES ('CP','0');

/*Ejemplo de tablas relacionadas.*/

DELETE p,c 
FROM PEDIDOS p
  LEFT JOIN COMPRAS c
  ON c.idpedido=p.idpedido
WHERE p.idpedido = '8037';


/*creacidon de tabla de falla - 24 de abril de 2018*/

CREATE TABLE FALLA (IDFALLA  INT AUTO_INCREMENT PRIMARY KEY,  IDPEDIDO VARCHAR(32) ,COMENTARIO VARCHAR(200), FECHAFALLA DATE);
